.PHONY: clean clean_all

clean:

	find . -name "*.aux" -exec rm {} \;
	find . -name "*.out" -exec rm {} \;
	find . -name "*.log" -exec rm {} \;
	find . -name "*.synctex.gz" -exec rm {} \;
	find . -name "*.toc" -exec rm {} \;
	find . -name "*.lof" -exec rm {} \;
	find . -name "*.lot" -exec rm {} \;

clean_all:

	find . -name "*.aux" -exec rm {} \;
	find . -name "*.out" -exec rm {} \;
	find . -name "*.log" -exec rm {} \;
	find . -name "*.synctex.gz" -exec rm {} \;
	find . -name "*.toc" -exec rm {} \;
	find . -name "*.lof" -exec rm {} \;
	find . -name "*.lot" -exec rm {} \;
	find . -name "*.pdf" -exec rm {} \;
